//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Driving_School_MS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        public int SessionId { get; set; }
        public string Day { get; set; }
        public System.DateTime Time { get; set; }
        public int NumberLearn { get; set; }
    }
}
